export const PrimaryTagChoices = [
  { label: "Accounting", value: "accounting" },
  { label: "Advertising", value: "advertising" },
  { label: "Agriculture", value: "agriculture" },
  { label: "Architecture", value: "architecture" },
  { label: "Assistance", value: "assistance" },
  { label: "Banking", value: "banking" },
  { label: "Business", value: "business" },
  { label: "Back End", value: "back-end" },
  { label: "Consultant", value: "consultant" },
  { label: "Customer Support", value: "customer-support" },
  { label: "Data Entry", value: "data-entry" },
  { label: "Design", value: "design" },
  { label: "Editing", value: "editing" },
  { label: "Engineering", value: "engineering" },
  { label: "Education", value: "education" },
  { label: "Economics & Finance", value: "economics-finance" },
  { label: "Front End", value: "front-end" },
  { label: "Graphic Design", value: "graphic-design" },
  { label: "Health", value: "health" },
  { label: "Leadership", value: "leadership" },
  { label: "Legal", value: "legal" },
  { label: "Marketing", value: "marketing" },
  { label: "No Code", value: "no-code" },
  { label: "Real Estate", value: "real-estate" },
  { label: "Sales", value: "sales" },
  { label: "Social Media", value: "social-media" },
  { label: "Translation", value: "translation" },
  { label: "Writing", value: "writing" },
  { label: "Other", value: "other" },
];
